# Resources 

## CRAN repository {.unnumbered}

- Website: https://cran.r-project.org/ 
- Current R Version: "Innocent and Trusting" 4.2.2
  - Released 10/31/2022

## R and RStudio Guides {.unnumbered}

- Downloading RStudio: 
  - Website: https://posit.co/download/rstudio-desktop/
- Downloading RTools:
  - Website: https://cran.r-project.org/bin/windows/Rtools/
- Posit Guides:
  - Keyboard Shortcut: https://support.posit.co/hc/en-us/articles/200711853-Keyboard-Shortcuts-in-the-RStudio-IDE
  - Cheatsheets: https://posit.co/resources/cheatsheets/
  
## Other R Package Guides {.unnumbered}
- gtsummary Documentation:
  - Tutorial: https://www.danieldsjoberg.com/gtsummary/articles/tbl_summary.html

## Data Visualization {.unnumbered}

- `ggplot2` Guide: https://r-graph-gallery.com/ggplot2-package.html
- `plotly` R Gallery (tutorials and documentation): https://plotly.com/r/
- R Colors: 
  - Colors in R Cheat Sheet: http://www.stat.columbia.edu/~tzheng/files/Rcolor.pdf
  - `ggplot2` color names: http://sape.inf.usi.ch/quick-reference/ggplot2/colour
  - Color Palettes: https://www.datanovia.com/en/blog/top-r-color-palettes-to-know-for-great-data-visualization/

## Example Datasets {.unnumbered}

The following list of data files are those retrieved from publicly available databases. The data files from CDC and WHO were contain only a sample of much larger datasets that are publicly available. 

- `Lowbwt_ALL.csv` is a dataset retrieved from CDC's public 2018 natality cohort dataset. 
- `IHD_WHO_Mortality.csv` is a dataset retrieved from WHO's (World Health Organization) public mortality database.
  - The data is for Ischemic Heart Disease (IHD) mortality data across all ages and all sexes for several countries. 
- `Odds_Ratio.csv` is a self-generated, random dataset used to help visualize Odds Ratio. 






